# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='omoney',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='omsg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ono',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
