# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20180523_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='gbuyers',
            field=models.ManyToManyField(null=True, to='MyApp.Buyer'),
        ),
    ]
