# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-23 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_auto_20180523_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ono',
        ),
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goods',
            name='gbuyers',
            field=models.ManyToManyField(to='MyApp.Buyer'),
        ),
    ]
